enable more mcp variant circleci optional presubmit tests

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -101,6 +101,42 @@ jobs:
       - store_test_results:
           path: /go/out/tests
 
+  e2e-simple-mcp:
+    <<: *integrationDefaults
+    environment:
+            - KUBECONFIG: /go/out/minikube.conf
+            - TEST_ENV: minikube-none
+            - GOPATH: /go
+    steps:
+      - <<: *initWorkingDir
+      - checkout
+      - attach_workspace:
+          at:  /go
+      - <<: *markJobStartsOnGCS
+      - run: make sync
+      - run: bin/testEnvRootMinikube.sh start
+      - run:
+          command: |
+            if [ ! -f /go/out/linux_amd64/release/pilot-discovery ]; then
+              # Should only happen when re-running a job, and the workspace is gone
+              time make build test-bins
+            fi
+            make docker.all
+      - run: bin/testEnvRootMinikube.sh wait
+      - run: docker images
+      - run: E2E_ARGS="--use_mcp" make test/local/auth/e2e_simple
+      - <<: *recordZeroExitCodeIfTestPassed
+      - <<: *recordNonzeroExitCodeIfTestFailed
+      - <<: *markJobFinishesOnGCS
+      - store_artifacts:
+          path: /home/circleci/logs
+      - store_artifacts:
+          path: /tmp
+      - store_artifacts:
+          path: /var/lib/localkube/
+      - store_test_results:
+          path: /go/out/tests
+
   e2e-dashboard:
     <<: *integrationDefaults
     environment:
@@ -128,6 +164,45 @@ jobs:
           command: |
             PATH=$GOPATH/bin:$PATH \
             E2E_ARGS="--skip_cleanup -use_local_cluster -test.v" \
+            set -o pipefail
+            make e2e_dashboard | tee -a /go/out/tests/build-log.txt
+      - <<: *recordZeroExitCodeIfTestPassed
+      - <<: *recordNonzeroExitCodeIfTestFailed
+      - <<: *markJobFinishesOnGCS
+      - store_artifacts:
+          path: /home/circleci/logs
+      - store_artifacts:
+          path: /tmp
+      - store_artifacts:
+          path: /var/lib/localkube/
+
+  e2e-dashboard-mcp:
+    <<: *integrationDefaults
+    environment:
+            - KUBECONFIG: /go/out/minikube.conf
+            - TEST_ENV: minikube-none
+            - GOPATH: /go
+    steps:
+      - <<: *initWorkingDir
+      - checkout
+      - attach_workspace:
+          at:  /go
+      - <<: *markJobStartsOnGCS
+      - run: make sync
+      - run: bin/testEnvRootMinikube.sh start
+      - run:
+          command: |
+            if [ ! -f /go/out/linux_amd64/release/pilot-discovery ]; then
+              # Should only happen when re-running a job, and the workspace is gone
+              time make build test-bins
+            fi
+            make docker.all generate_yaml
+      - run: bin/testEnvRootMinikube.sh wait
+      - run: docker images
+      - run:
+          command: |
+            PATH=$GOPATH/bin:$PATH \
+            E2E_ARGS="--skip_cleanup -use_local_cluster --use_mcp -test.v" \
             set -o pipefail
             make e2e_dashboard | tee -a /go/out/tests/build-log.txt
       - <<: *recordZeroExitCodeIfTestPassed
@@ -304,6 +379,46 @@ jobs:
           # Run the test even if previous failed
           when: always
           command: |
+                make test/local/noauth/e2e_pilotv2
+      - <<: *recordZeroExitCodeIfTestPassed
+      - <<: *recordNonzeroExitCodeIfTestFailed
+      - <<: *markJobFinishesOnGCS
+      - store_test_results:
+          path: /go/out/tests
+      - store_artifacts:
+          path: /go/out/logs
+      - store_artifacts:
+          path: /tmp
+
+  e2e-pilot-noauth-v1alpha3-v2-mcp:
+    <<: *integrationDefaults
+    environment:
+            - GOPATH: /go
+            - KUBECONFIG: /go/out/minikube.conf
+            - TEST_ENV: minikube-none
+    steps:
+      - <<: *initWorkingDir
+      - checkout
+      - attach_workspace:
+          at:  /go
+      - <<: *markJobStartsOnGCS
+      - run: make sync
+      - run: bin/testEnvRootMinikube.sh start
+      - run:
+          command: |
+            if [ ! -f /go/out/linux_amd64/release/pilot-discovery ]; then
+              # Should only happen when re-running a job, and the workspace is gone
+              time make build test-bins
+            fi
+            make docker.all generate_yaml
+      - run: bin/testEnvRootMinikube.sh wait
+      - run: docker images
+      - run:
+          no_output_timeout: 20m
+          # Run the test even if previous failed
+          when: always
+          command: |
+                E2E_ARGS="--use_mcp" \
                 make test/local/noauth/e2e_pilotv2
       - <<: *recordZeroExitCodeIfTestPassed
       - <<: *recordNonzeroExitCodeIfTestFailed
@@ -648,7 +763,13 @@ workflows:
       - e2e-simple:
           requires:
             - build
+      - e2e-simple-mcp:
+          requires:
+            - build
       - e2e-dashboard:
+          requires:
+            - build
+      - e2e-dashboard-mcp:
           requires:
             - build
       - benchcheck:
@@ -668,6 +789,9 @@ workflows:
           requires:
             - test
       - e2e-pilot-noauth-v1alpha3-v2: # no auth+v1alpha3+v2
+          requires:
+            - build
+      - e2e-pilot-noauth-v1alpha3-v2-mcp: # no auth+v1alpha3+v2
           requires:
             - build
       - e2e-pilot-auth-v1alpha3-v2: # auth+v1alpha3+v2
@@ -696,6 +820,9 @@ workflows:
       - e2e-simple:
           requires:
             - build
+      - e2e-simple-mcp:
+          requires:
+            - build
       - racetest:
           requires:
             - test
@@ -706,6 +833,9 @@ workflows:
           requires:
             - build
       - e2e-pilot-noauth-v1alpha3-v2: # noauth+v1alpha3+v2
+          requires:
+            - build
+      - e2e-pilot-noauth-v1alpha3-v2-mcp: # noauth+v1alpha3+v2 with MCP
           requires:
             - build
       - e2e-pilot-cloudfoundry-v1alpha3-v2:
