CNI Plugin and daemonset work (#159)
* sync cni and master branches

* WIP: initial daemonset work

* start refactor, move net utils and start adding route table maintainence

* label selector work

* update api dep, move disabled selector to meshconfig, some more cleanup

* sync cni and master branches

* WIP: initial daemonset work

* start refactor, move net utils and start adding route table maintainence

* label selector work

* update api dep, move disabled selector to meshconfig, some more cleanup

* add uproxy rules to init container

* WIP

* finish networking setup

* WIP

* fix cni plugin

* merge DSs and disable rp filter on iptables mode

* remove ClusterFirstWithHostNet

* fix render

* cherry pick and merge ambient changes to init container

* clean ups

* working push, update readme

* changes to informers

* test fixes

* readd cmddel func, test fix

* make gen

* remove script tests

* remove test script

* fix for CI job, update rules per Yuval's work

* change constants to camelcase

* add cleanup of ip rules to init

* change rule numbers

* change ipset comment to pod's UID, debug unit test for ipset

* remove ipset unit test debug, add comment above masks on why they are included

* add mutex locking

* add dns capture, change ipset unit test for kernels that don't support comments

* fixes to rules and comments to map where in the script the code originates

* linting

* more linting

* test: need to label namespace for ambient mesh

* Revert "test: need to label namespace for ambient mesh"

This reverts commit 6f019b63f07b073bd7148b04a1e650cce58649fb.

* We need host ip when removing the route of a pod

* enabled ambientMode for ambient integration tests

* fixes

* fix readme

* add check for ambient mesh in mesh config before using it

* integ pod terminations were not being cleaned correctly

* fix dns capture, and fix int test for ambient

* linting

* more linting

* remove a todo

* more linting

* fix cleanup of uproxy rules on deletion of uproxy pod

* move logs for uproxy to uproxy's init container

* fix ambient.yaml log entries to be after flush

* clean up the cleanup

* reconcile namespaces after uproxy starts

* more fixes

* fix uproxyrunning check in plugin

* lint changes

* add more logging for CI

* Also clean up mangle's uproxy-POSTROUTING chain.

* rp_filter for istio links

* add interim per-pod opt out, currently just ambient-type=pep

* Update setup.sh for CNI and DNS capture (#191)

* ignore ambient-type=none as well

* uncomment sidecar in integ test

* remove no longer needed comment

Co-authored-by: Yuval Kohavi <yuval.kohavi@gmail.com>
Co-authored-by: Greg Hanson <gregory.hanson@solo.io>
Co-authored-by: Aaron Birkland <aaron.birkland@solo.io>

diff --git a/manifests/charts/istio-control/istio-discovery/templates/ambient.yaml b/manifests/charts/istio-control/istio-discovery/templates/ambient.yaml
--- a/manifests/charts/istio-control/istio-discovery/templates/ambient.yaml
+++ b/manifests/charts/istio-control/istio-discovery/templates/ambient.yaml
@@ -65,12 +65,22 @@ spec:
         {{- end }}
     spec:
       serviceAccountName: uproxy
+      tolerations:
+        - effect: NoSchedule
+          operator: Exists
+        - key: CriticalAddonsOnly
+          operator: Exists
+        - effect: NoExecute
+          operator: Exists
       initContainers:
       - name: istio-init
 {{- if contains "/" .Values.uproxy.image }}
         image: "{{ .Values.uproxy.image }}"
 {{- else }}
         image: "{{ .Values.uproxy.hub | default .Values.global.hub }}/{{ .Values.uproxy.image | default "proxyv2" }}:{{ .Values.uproxy.tag | default .Values.global.tag }}"
+{{- end }}
+{{- if .Values.global.imagePullPolicy }}
+        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
 {{- end }}
         securityContext:
           privileged: true
@@ -80,15 +90,138 @@ spec:
         command:
           - sh
           - -c
-{{- if $iptablesRedirect }}
           - |
+            # START https://github.com/solo-io/istio-sidecarless/blob/master/redirect-worker.sh#L198-L205
+            PROXY_OUTBOUND_MARK=0x401/0xfff
+            PROXY_INBOUND_MARK=0x402/0xfff
+            PROXY_ORG_SRC_MARK=0x4d2/0xfff
+            # tproxy mark, it's only used here.
+            MARK=0x400/0xfff
+            ORG_SRC_RET_MARK=0x4d3/0xfff
+            # END https://github.com/solo-io/istio-sidecarless/blob/master/redirect-worker.sh#L198-L205
+
+            # Below is from config.sh but used in redirect-worker.sh as well
+            POD_OUTBOUND=15001
+            POD_INBOUND=15008
+            POD_INBOUND_PLAINTEXT=15006
+
+            # socket mark setup
+            OUTBOUND_MASK="0x100"
+            OUTBOUND_MARK="0x100/$OUTBOUND_MASK"
+
+            SKIP_MASK="0x200"
+            SKIP_MARK="0x200/$SKIP_MASK"
+
+            # note!! this includes the skip mark bit, so match on skip mark will match this as well.
+            CONNSKIP_MASK="0x220"
+            CONNSKIP_MARK="0x220/$CONNSKIP_MASK"
+
+            # note!! this includes the skip mark bit, so match on skip mark will match this as well.
+            PROXY_MASK="0x210"
+            PROXY_MARK="0x210/$PROXY_MASK"
+
+            PROXY_RET_MASK="0x040"
+            PROXY_RET_MARK="0x040/$PROXY_RET_MASK"
+
+            INBOUND_TUN=istioin
+            OUTBOUND_TUN=istioout
+
+            # TODO: look into why link local (169.254.x.x) address didn't work
+            # they don't respond to ARP.
+            INBOUND_TUN_IP=192.168.126.1
+            UPROXY_INBOUND_TUN_IP=192.168.126.2
+            OUTBOUND_TUN_IP=192.168.127.1
+            UPROXY_OUTBOUND_TUN_IP=192.168.127.2
+            TUN_PREFIX=30
+
+            # a route table number number we can use to send traffic to envoy (should be unused).
+            INBOUND_ROUTE_TABLE=100
+            INBOUND_ROUTE_TABLE2=103
+            OUTBOUND_ROUTE_TABLE=101
+            # needed for original src.
+            PROXY_ROUTE_TABLE=102
+
+            # We need the veth ip from the host to setup the tunnel
+            HOST_IP=$(ip route | grep default | awk '{print $3}')
+
+            # START https://github.com/solo-io/istio-sidecarless/blob/master/redirect-worker.sh#L185-L196
+            set +e # Only for delete, we don't care if this fails
+            ip link del p$INBOUND_TUN
+            ip link del p$OUTBOUND_TUN
+            set -e
+
+            ip link add name p$INBOUND_TUN type geneve id 1000 remote $HOST_IP
+            ip addr add $UPROXY_INBOUND_TUN_IP/$TUN_PREFIX dev p$INBOUND_TUN
+
+            ip link add name p$OUTBOUND_TUN type geneve id 1001 remote $HOST_IP
+            ip addr add $UPROXY_OUTBOUND_TUN_IP/$TUN_PREFIX dev p$OUTBOUND_TUN
+
+            ip link set p$INBOUND_TUN up
+            ip link set p$OUTBOUND_TUN up
+
+            echo 0 > /proc/sys/net/ipv4/conf/p$INBOUND_TUN/rp_filter
+            echo 0 > /proc/sys/net/ipv4/conf/p$OUTBOUND_TUN/rp_filter
+            # END https://github.com/solo-io/istio-sidecarless/blob/master/redirect-worker.sh#L185-L196
+
+            # START https://github.com/solo-io/istio-sidecarless/blob/master/redirect-worker.sh#L206-L238
+            set +e # Only for delete, we don't care if this fails
+            ip rule del priority 20000
+            ip rule del priority 20001
+            ip rule del priority 20002
+            ip rule del priority 20003
+
+            ip route flush table 100
+            ip route flush table 101
+            ip route flush table 102
+            set -e
+
+            ip rule add priority 20000 fwmark $MARK lookup 100
+            ip rule add priority 20001 fwmark $PROXY_OUTBOUND_MARK lookup 101
+            ip rule add priority 20002 fwmark $PROXY_INBOUND_MARK lookup 102
+            ip rule add priority 20003 fwmark $ORG_SRC_RET_MARK lookup 100
+            ip route add local 0.0.0.0/0 dev lo table 100
+
+            ip route add table 101 $HOST_IP dev eth0 scope link
+            ip route add table 101 0.0.0.0/0 via $OUTBOUND_TUN_IP dev p$OUTBOUND_TUN
+
+            ip route add table 102 $HOST_IP dev eth0 scope link
+            ip route add table 102 0.0.0.0/0 via $INBOUND_TUN_IP dev p$INBOUND_TUN
+
+            iptables -t mangle -F PREROUTING
+            iptables -t nat -F OUTPUT
+
+            iptables-save | grep -v LOG | iptables-restore
+            iptables -t mangle -I PREROUTING -j LOG --log-prefix "mangle pre [$POD_NAME] "
+            iptables -t mangle -I POSTROUTING -j LOG --log-prefix "mangle post [$POD_NAME] "
+            iptables -t mangle -I INPUT -j LOG --log-prefix "mangle inp [$POD_NAME] "
+            iptables -t mangle -I OUTPUT -j LOG --log-prefix "mangle out [$POD_NAME] "
+            iptables -t mangle -I FORWARD -j LOG --log-prefix "mangle fw [$POD_NAME] "
+            iptables -t nat -I POSTROUTING -j LOG --log-prefix "nat post [$POD_NAME] "
+            iptables -t nat -I INPUT -j LOG --log-prefix "nat inp [$POD_NAME] "
+            iptables -t nat -I OUTPUT -j LOG --log-prefix "nat out [$POD_NAME] "
+            iptables -t nat -I PREROUTING -j LOG --log-prefix "nat pre [$POD_NAME] "
+            iptables -t raw -I PREROUTING -j LOG --log-prefix "raw pre [$POD_NAME] "
+            iptables -t raw -I OUTPUT -j LOG --log-prefix "raw out [$POD_NAME] "
+            iptables -t filter -I FORWARD -j LOG --log-prefix "filt fw [$POD_NAME] "
+            iptables -t filter -I OUTPUT -j LOG --log-prefix "filt out [$POD_NAME] "
+            iptables -t filter -I INPUT -j LOG --log-prefix "filt inp [$POD_NAME] "
+
+            iptables -t mangle -A PREROUTING -p tcp -i p$INBOUND_TUN -m tcp --dport=$POD_INBOUND -j TPROXY --tproxy-mark $MARK --on-port $POD_INBOUND --on-ip 127.0.0.1
+            iptables -t mangle -A PREROUTING -p tcp -i p$OUTBOUND_TUN -j TPROXY --tproxy-mark $MARK --on-port $POD_OUTBOUND --on-ip 127.0.0.1
+            iptables -t mangle -A PREROUTING -p tcp -i p$INBOUND_TUN -j TPROXY --tproxy-mark $MARK --on-port $POD_INBOUND_PLAINTEXT --on-ip 127.0.0.1
+
+            iptables -t mangle -A PREROUTING -p tcp -i eth0 ! --dst $INSTANCE_IP -j MARK --set-mark $ORG_SRC_RET_MARK
+
+            iptables -t nat -A OUTPUT -p tcp --dport 15088 -j REDIRECT --to-port $POD_INBOUND
+            # END https://github.com/solo-io/istio-sidecarless/blob/master/redirect-worker.sh#L206-L238
+{{- if $iptablesRedirect }}
             # With normal linux routing we need to disable the rp_filter
             # as we get packets from a tunnel that doesn't have default routes.
             echo 0 > /proc/sys/net/ipv4/conf/all/rp_filter
             echo 0 > /proc/sys/net/ipv4/conf/default/rp_filter
             echo 0 > /proc/sys/net/ipv4/conf/eth0/rp_filter
 {{- else }}
-          - |
+            # MTP traffic goes to MTP port...
             # HBONE traffic goes to HBONE port...
             iptables -t nat -A PREROUTING -p tcp --dport 15008 ! -s $INSTANCE_IP ! -d $INSTANCE_IP  -j LOG --log-prefix="[howardjohn 15008] "
             iptables -t nat -A PREROUTING -p tcp --dport 15008 ! -s $INSTANCE_IP ! -d $INSTANCE_IP  -j REDIRECT --to-ports 15008
@@ -111,6 +244,16 @@ spec:
           valueFrom:
             fieldRef:
               fieldPath: status.podIP
+        - name: POD_NAME
+          valueFrom:
+            fieldRef:
+              fieldPath: metadata.name
+        {{- if .Values.meshConfig.defaultConfig.proxyMetadata }}
+        {{- range $key, $value := .Values.meshConfig.defaultConfig.proxyMetadata}}
+        - name: {{ $key }}
+          value: "{{ $value }}"
+        {{- end }}
+        {{- end }}
         {{- if .Values.uproxy.env }}
         {{- range $key, $val := .Values.uproxy.env }}
         - name: {{ $key }}
@@ -167,6 +310,12 @@ spec:
           valueFrom:
             fieldRef:
               fieldPath: spec.serviceAccountName
+        {{- if .Values.meshConfig.defaultConfig.proxyMetadata }}
+        {{- range $key, $value := .Values.meshConfig.defaultConfig.proxyMetadata}}
+        - name: {{ $key }}
+          value: "{{ $value }}"
+        {{- end }}
+        {{- end }}
         {{- if .Values.uproxy.env }}
         {{- range $key, $val := .Values.uproxy.env }}
         - name: {{ $key }}
